"""Order models for Binance Thailand API.

This module defines Pydantic models for order creation,
querying, and management.

IMPORTANT - Authentication Parameters:
    All SIGNED endpoints (orders, account, etc.) require these parameters:
    - timestamp: Millisecond timestamp when request is created
    - signature: HMAC SHA256 signature of all request parameters

    These are NOT included in request models because they are
    AUTO-GENERATED by the REST client at request time:

    1. timestamp = current_time_ms + server_time_offset
    2. signature = HMAC_SHA256(all_params_as_query_string, api_secret)

    Example of what the client sends:
        POST /api/v1/order?symbol=BTCUSDT&side=BUY&type=LIMIT&quantity=0.001
            &price=50000&timeInForce=GTC&timestamp=1234567890123
            &signature=abc123...

    The user only needs to provide the business parameters (symbol, side, etc.),
    and the client handles authentication automatically.
"""

from decimal import Decimal

from pydantic import Field, model_validator

from binance_th.models.base import RequestModel, ResponseModel
from binance_th.models.enums import OrderSide, OrderStatus, OrderType, TimeInForce


class Order(ResponseModel):
    """Order information response.

    Response from POST/GET/DELETE /api/v1/order
    Contains full order details including execution status.
    """

    symbol: str = Field(description="Trading pair symbol")
    order_id: int = Field(alias="orderId", description="Order ID")
    order_list_id: int = Field(
        alias="orderListId",
        default=-1,
        description="Order list ID (-1 if not OCO)",
    )
    client_order_id: str = Field(alias="clientOrderId", description="Client order ID")
    price: Decimal = Field(description="Order price")
    orig_qty: Decimal = Field(alias="origQty", description="Original quantity")
    executed_qty: Decimal = Field(alias="executedQty", description="Executed quantity")
    cummulative_quote_qty: Decimal = Field(
        alias="cummulativeQuoteQty",
        description="Cumulative quote quantity filled",
    )
    status: OrderStatus = Field(description="Order status")
    time_in_force: TimeInForce = Field(alias="timeInForce", description="Time in force")
    order_type: OrderType = Field(alias="type", description="Order type")
    side: OrderSide = Field(description="Order side (BUY/SELL)")
    stop_price: Decimal | None = Field(
        alias="stopPrice",
        default=None,
        description="Stop price for stop orders",
    )
    time: int = Field(description="Order creation timestamp")
    update_time: int = Field(alias="updateTime", description="Last update timestamp")
    is_working: bool = Field(alias="isWorking", description="Order is working on book")
    orig_quote_order_qty: Decimal = Field(
        alias="origQuoteOrderQty",
        description="Original quote order quantity",
    )

    @property
    def is_filled(self) -> bool:
        """Check if order is completely filled."""
        return self.status == OrderStatus.FILLED

    @property
    def is_active(self) -> bool:
        """Check if order is still active (can be filled)."""
        return self.status in (OrderStatus.NEW, OrderStatus.PARTIALLY_FILLED)

    @property
    def filled_percent(self) -> Decimal:
        """Get percentage of order filled."""
        if self.orig_qty == 0:
            return Decimal("0")
        return (self.executed_qty / self.orig_qty) * 100


class OrderRequest(RequestModel):
    """Request model for creating new orders.

    Used with POST /api/v1/order

    API Parameters (from official documentation):
    ┌─────────────────────┬─────────────┬─────────────────────────────────────────┐
    │ Parameter           │ Required    │ Notes                                   │
    ├─────────────────────┼─────────────┼─────────────────────────────────────────┤
    │ symbol              │ MANDATORY   │ Trading pair (e.g., BTCUSDT)            │
    │ side                │ MANDATORY   │ BUY or SELL                             │
    │ type                │ MANDATORY   │ Order type (LIMIT, MARKET, etc.)        │
    │ timestamp           │ MANDATORY   │ * Auto-generated by client              │
    │ timeInForce         │ Optional    │ Required for LIMIT orders               │
    │ quantity            │ Optional    │ Base asset amount                       │
    │ quoteOrderQty       │ Optional    │ Quote asset amount (for MARKET)         │
    │ price               │ Optional    │ Required for LIMIT orders               │
    │ newClientOrderId    │ Optional    │ Custom order ID                         │
    │ stopPrice           │ Optional    │ Required for STOP orders                │
    │ recvWindow          │ Optional    │ Max 60000ms, default 5000ms             │
    │ signature           │ MANDATORY   │ * Auto-generated by client              │
    └─────────────────────┴─────────────┴─────────────────────────────────────────┘

    * timestamp and signature are auto-generated by the REST client

    Example:
        >>> request = OrderRequest(
        ...     symbol="BTCUSDT",
        ...     side=OrderSide.BUY,
        ...     order_type=OrderType.LIMIT,
        ...     quantity=Decimal("0.001"),
        ...     price=Decimal("50000"),
        ...     time_in_force=TimeInForce.GTC,
        ... )
    """

    symbol: str = Field(description="Trading pair symbol (MANDATORY)")
    side: OrderSide = Field(description="Order side: BUY or SELL (MANDATORY)")
    order_type: OrderType = Field(alias="type", description="Order type (MANDATORY)")
    time_in_force: TimeInForce | None = Field(
        default=None,
        alias="timeInForce",
        description="Time in force - required for LIMIT orders",
    )
    quantity: Decimal | None = Field(
        default=None,
        description="Order quantity in base asset",
    )
    quote_order_qty: Decimal | None = Field(
        default=None,
        alias="quoteOrderQty",
        description="Order quantity in quote asset (alternative to quantity)",
    )
    price: Decimal | None = Field(
        default=None,
        description="Order price (required for LIMIT orders)",
    )
    new_client_order_id: str | None = Field(
        default=None,
        alias="newClientOrderId",
        description="Custom client order ID (auto-generated if not provided)",
    )
    stop_price: Decimal | None = Field(
        default=None,
        alias="stopPrice",
        description="Stop price (required for STOP_LOSS, TAKE_PROFIT orders)",
    )
    recv_window: int | None = Field(
        default=None,
        alias="recvWindow",
        description="Request validity window in ms (max 60000)",
        le=60000,
    )

    @model_validator(mode="after")
    def validate_order_params(self) -> "OrderRequest":
        """Validate order parameters based on order type.

        Raises:
            ValueError: If required parameters are missing for order type
        """
        # LIMIT orders require price and timeInForce
        if self.order_type == OrderType.LIMIT:
            if self.price is None:
                raise ValueError("price is required for LIMIT orders")
            if self.time_in_force is None:
                raise ValueError("timeInForce is required for LIMIT orders")
            if self.quantity is None:
                raise ValueError("quantity is required for LIMIT orders")

        # MARKET orders require either quantity or quoteOrderQty
        if (
            self.order_type == OrderType.MARKET
            and self.quantity is None
            and self.quote_order_qty is None
        ):
            raise ValueError("Either quantity or quoteOrderQty is required for MARKET orders")

        # STOP orders require stopPrice
        if (
            self.order_type
            in (
                OrderType.STOP_LOSS,
                OrderType.STOP_LOSS_LIMIT,
                OrderType.TAKE_PROFIT,
                OrderType.TAKE_PROFIT_LIMIT,
            )
            and self.stop_price is None
        ):
            raise ValueError("stopPrice is required for STOP orders")

        # STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT require price and timeInForce
        if self.order_type in (OrderType.STOP_LOSS_LIMIT, OrderType.TAKE_PROFIT_LIMIT):
            if self.price is None:
                raise ValueError("price is required for limit stop orders")
            if self.time_in_force is None:
                raise ValueError("timeInForce is required for limit stop orders")

        return self


class CancelOrderRequest(RequestModel):
    """Request model for canceling orders.

    Used with DELETE /api/v1/order

    API Parameters (from official documentation):
    ┌─────────────────────┬─────────────┬─────────────────────────────────────────┐
    │ Parameter           │ Required    │ Notes                                   │
    ├─────────────────────┼─────────────┼─────────────────────────────────────────┤
    │ symbol              │ MANDATORY   │ Trading pair                            │
    │ timestamp           │ MANDATORY   │ * Auto-generated by client              │
    │ orderId             │ Optional    │ Either this or origClientOrderId        │
    │ origClientOrderId   │ Optional    │ Either this or orderId                  │
    │ recvWindow          │ Optional    │ Max 60000ms                             │
    │ signature           │ MANDATORY   │ * Auto-generated by client              │
    └─────────────────────┴─────────────┴─────────────────────────────────────────┘

    * timestamp and signature are auto-generated by the REST client
    """

    symbol: str = Field(description="Trading pair symbol (MANDATORY)")
    order_id: int | None = Field(
        default=None,
        alias="orderId",
        description="Order ID to cancel",
    )
    orig_client_order_id: str | None = Field(
        default=None,
        alias="origClientOrderId",
        description="Original client order ID to cancel",
    )
    recv_window: int | None = Field(
        default=None,
        alias="recvWindow",
        description="Request validity window in ms (max 60000)",
        le=60000,
    )

    @model_validator(mode="after")
    def validate_order_identifier(self) -> "CancelOrderRequest":
        """Validate that at least one order identifier is provided.

        Raises:
            ValueError: If neither orderId nor origClientOrderId is provided
        """
        if self.order_id is None and self.orig_client_order_id is None:
            raise ValueError("Either orderId or origClientOrderId is required")
        return self


class QueryOrderRequest(RequestModel):
    """Request model for querying order status.

    Used with GET /api/v1/order

    API Parameters (from official documentation):
    ┌─────────────────────┬─────────────┬─────────────────────────────────────────┐
    │ Parameter           │ Required    │ Notes                                   │
    ├─────────────────────┼─────────────┼─────────────────────────────────────────┤
    │ symbol              │ MANDATORY   │ Trading pair                            │
    │ timestamp           │ MANDATORY   │ * Auto-generated by client              │
    │ orderId             │ Optional    │ Either this or origClientOrderId        │
    │ origClientOrderId   │ Optional    │ Either this or orderId                  │
    │ recvWindow          │ Optional    │ Max 60000ms                             │
    │ signature           │ MANDATORY   │ * Auto-generated by client              │
    └─────────────────────┴─────────────┴─────────────────────────────────────────┘

    * timestamp and signature are auto-generated by the REST client
    """

    symbol: str = Field(description="Trading pair symbol (MANDATORY)")
    order_id: int | None = Field(
        default=None,
        alias="orderId",
        description="Order ID to query",
    )
    orig_client_order_id: str | None = Field(
        default=None,
        alias="origClientOrderId",
        description="Original client order ID to query",
    )
    recv_window: int | None = Field(
        default=None,
        alias="recvWindow",
        description="Request validity window in ms (max 60000)",
        le=60000,
    )

    @model_validator(mode="after")
    def validate_order_identifier(self) -> "QueryOrderRequest":
        """Validate that at least one order identifier is provided.

        Raises:
            ValueError: If neither orderId nor origClientOrderId is provided
        """
        if self.order_id is None and self.orig_client_order_id is None:
            raise ValueError("Either orderId or origClientOrderId is required")
        return self
